/*
* generated by Xtext
*/
package eclihx.hxml.contentassist;

import eclihx.hxml.contentassist.AbstractHXmlProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class HXmlProposalProvider extends AbstractHXmlProposalProvider {

}
