/*
* generated by Xtext
*/
package eclihx.hxml.outline;

import org.eclipse.xtext.ui.common.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class HXmlTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
