/*
 * generated by Xtext
 */
package eclihx.hxml;

/**
 * Use this class to register components to be used within the IDE.
 */
public class HXmlRuntimeModule extends eclihx.hxml.AbstractHXmlRuntimeModule {

}
