/* Generated By:JJTree&JavaCC: Do not edit this line. eg2Constants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
@SuppressWarnings("all")
public interface eg2Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 7;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 8;
  /** RegularExpression Id. */
  int HEX_LITERAL = 9;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 10;
  /** RegularExpression Id. */
  int CLASSNAME = 11;
  /** RegularExpression Id. */
  int IDENTIFIER = 12;
  /** RegularExpression Id. */
  int LETTER_MAJ = 13;
  /** RegularExpression Id. */
  int LETTER = 14;
  /** RegularExpression Id. */
  int DIGIT = 15;
  /** RegularExpression Id. */
  int ID_HEAD = 16;
  /** RegularExpression Id. */
  int ID_TAIL = 17;
  /** RegularExpression Id. */
  int STRING_CHAR_A = 18;
  /** RegularExpression Id. */
  int STRING_CHAR_B = 19;
  /** RegularExpression Id. */
  int REGEX_CHAR = 20;
  /** RegularExpression Id. */
  int HEX_NUMBER = 21;
  /** RegularExpression Id. */
  int IDENT = 22;
  /** RegularExpression Id. */
  int STRLIST = 23;
  /** RegularExpression Id. */
  int REGEXLIST = 24;
  /** RegularExpression Id. */
  int DECLIST = 25;
  /** RegularExpression Id. */
  int HEXLIST = 26;
  /** RegularExpression Id. */
  int BOOLLIST = 27;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<CLASSNAME>",
    "<IDENTIFIER>",
    "<LETTER_MAJ>",
    "<LETTER>",
    "<DIGIT>",
    "<ID_HEAD>",
    "<ID_TAIL>",
    "<STRING_CHAR_A>",
    "<STRING_CHAR_B>",
    "<REGEX_CHAR>",
    "<HEX_NUMBER>",
    "<IDENT>",
    "<STRLIST>",
    "<REGEXLIST>",
    "<DECLIST>",
    "<HEXLIST>",
    "<BOOLLIST>",
    "\"var \"",
    "\"=\"",
    "\";\"",
    "\"php.Lib.print(\\\'Hello \\\' + name + \\\'!\\\');\"",
    "\"php.Web.getParams()\"",
    "\"params.exists(\\\'name\\\') ? params.get(\\\'name\\\') : \\\'world\\\'\"",
    "\"static function main() {\"",
    "\"package \"",
    "\"class \"",
    "\"{\"",
    "\"}\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"(\"",
    "\")\"",
  };

}
