/* Generated By:JavaCC: Do not edit this line. eg2TreeConstants.java Version 5.0 */
@SuppressWarnings("all")
public interface eg2TreeConstants
{
  public int JJTSTART = 0;
  public int JJTMYEXPRESSION = 1;
  public int JJTVALEUR = 2;
  public int JJTBEGINMETHODMAIN = 3;
  public int JJTPACKAGE = 4;
  public int JJTBEGINCLASS = 5;
  public int JJTEND = 6;
  public int JJTEXPRESSION = 7;
  public int JJTADDITIVEEXPRESSION = 8;
  public int JJTMULTIPLICATIVEEXPRESSION = 9;
  public int JJTUNARYEXPRESSION = 10;
  public int JJTIDENTIFIER = 11;
  public int JJTINTEGER = 12;


  public String[] jjtNodeName = {
    "Start",
    "MyExpression",
    "Valeur",
    "BeginMethodMain",
    "Package",
    "BeginClass",
    "End",
    "Expression",
    "AdditiveExpression",
    "MultiplicativeExpression",
    "UnaryExpression",
    "Identifier",
    "Integer",
  };
}
/* JavaCC - OriginalChecksum=274deba51d1c4148b5ca150dc1a75634 (do not edit this line) */
