<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="hxml"
    nsURI="http://www.xtext.org/example/HXml" nsPrefix="hxml">
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//Type" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Classpath" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="Javascript" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="Swf" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="Swf9" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="Neko" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="Php" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="Cpp" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="Xml" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="Main" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="Lib" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="Flag" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="Verbose" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="Debug" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="Type">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
